spring:
  application:
    name: TaskManager
  datasource:
    url: jdbc:postgresql://localhost:5432/task_manager
    username: postgres
    password: cfifhtgnjh8
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  kafka:
    topic:
      audit-events: audit-events
jwt:
  expiration:
    ms: 900000
  secret: dGhpcyBpcyBhIHN1cGVyIHNlY3VyZSAyNTYgYml0cyBrZXkgZm9yIEhTMjU2IQ==